// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iujbivlvqqciqnanwzfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1amJpdmx2cXFjaXFuYW53emZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTExNzIsImV4cCI6MjA2MzY2NzE3Mn0.goBV2ZrpacJxwJCHAjKlmYtI1J0h4mB5uZ5PNE-lBkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);